# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./sc2kfix.sln

permissions:
  contents: read

jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sc2kfix-dev
        path: |
          Release/winmm.dll
          Release/mods/*.dll

    - name: Build ReleaseKuroko
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=ReleaseKuroko /t:Rebuild ${{env.SOLUTION_FILE_PATH}}

    - name: Upload ReleaseKuroko Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sc2kfix-dev-kuroko
        path: |
          ReleaseKuroko/winmm.dll
          ReleaseKuroko/mods/*.dll
